/**
 * Column lists and the value/object builders that flatten a domain object into ordered INSERT values.
 * Also the sparse-delta flattening for endpoint patches and state transitions. Shared so the adapters
 * cannot drift on column order or jsonb handling.
 *
 * Each builder comes in a raw and a stringified form; the executor's `jsonAsText` seam picks between
 * them (see `../sql-store`). Every bundled adapter sets `jsonAsText: true`, so jsonb params are
 * pre-stringified against the `::jsonb` cast — binding them as raw objects is what broke top-level
 * `null`/string/array payloads on pg and Drizzle before 0.4.0. The raw form is kept only for a future
 * non-Postgres binding.
 */
import type { Transition } from "../../core/index";
import type { NewOutboxRow, NewDeliveryAttempt, NewEndpointRow, EndpointPatch } from "../store";

/** Outbox columns in INSERT order (shared so the adapters cannot drift). */
export const OUTBOX_COLUMNS = [
  "id",
  "event_type",
  "payload",
  "endpoint_id",
  "target_url",
  "secret_snapshot",
  "status",
  "attempts",
  "available_at",
  "idempotency_key",
] as const;

/** Ordered values matching {@link OUTBOX_COLUMNS} for a parameterised (pg) INSERT. */
export function outboxValues(row: NewOutboxRow): unknown[] {
  return [
    row.id,
    row.eventType,
    row.payload,
    row.endpointId,
    row.targetUrl,
    row.secretSnapshot,
    row.status,
    row.attempts,
    row.availableAt,
    row.idempotencyKey,
  ];
}

/** Object form for a knex INSERT; `payload` is stringified for the jsonb column. */
export function outboxObject(row: NewOutboxRow): Record<string, unknown> {
  return {
    id: row.id,
    event_type: row.eventType,
    payload: JSON.stringify(row.payload),
    endpoint_id: row.endpointId,
    target_url: row.targetUrl,
    secret_snapshot: row.secretSnapshot,
    status: row.status,
    attempts: row.attempts,
    available_at: row.availableAt,
    idempotency_key: row.idempotencyKey,
  };
}

/** Attempt columns in INSERT order. `id` is generated by the caller; `attempted_at` defaults to now(). */
export const ATTEMPT_COLUMNS = [
  "id",
  "outbox_id",
  "attempt_no",
  "request_headers",
  "response_status",
  "response_body_snippet",
  "duration_ms",
  "error",
] as const;

/** Ordered values matching {@link ATTEMPT_COLUMNS} for a parameterised (pg) INSERT. */
export function attemptValues(id: string, a: NewDeliveryAttempt): unknown[] {
  return [
    id,
    a.outboxId,
    a.attemptNo,
    a.requestHeaders,
    a.responseStatus,
    a.responseBodySnippet,
    a.durationMs,
    a.error,
  ];
}

/** Object form for a knex INSERT; `request_headers` is stringified for the jsonb column. */
export function attemptObject(id: string, a: NewDeliveryAttempt): Record<string, unknown> {
  return {
    id,
    outbox_id: a.outboxId,
    attempt_no: a.attemptNo,
    request_headers: JSON.stringify(a.requestHeaders),
    response_status: a.responseStatus,
    response_body_snippet: a.responseBodySnippet,
    duration_ms: a.durationMs,
    error: a.error,
  };
}

/** Endpoint columns in INSERT order. `metadata`/`custom_headers` are the jsonb columns. */
export const ENDPOINT_COLUMNS = [
  "id",
  "url",
  "secret",
  "description",
  "metadata",
  "custom_headers",
] as const;

/** Ordered values matching {@link ENDPOINT_COLUMNS} for a parameterised (pg) INSERT. */
export function endpointValues(ep: NewEndpointRow): unknown[] {
  return [
    ep.id,
    ep.url,
    ep.secret,
    ep.description ?? null,
    ep.metadata ?? null,
    ep.customHeaders ?? null,
  ];
}

/** Object form for an endpoint INSERT under `jsonAsText`; the jsonb columns are stringified. */
export function endpointObject(ep: NewEndpointRow): Record<string, unknown> {
  return {
    id: ep.id,
    url: ep.url,
    secret: ep.secret,
    description: ep.description ?? null,
    metadata: ep.metadata != null ? JSON.stringify(ep.metadata) : null,
    custom_headers: ep.customHeaders != null ? JSON.stringify(ep.customHeaders) : null,
  };
}

const ENDPOINT_PATCH_COLUMN: Record<keyof EndpointPatch, string> = {
  url: "url",
  secret: "secret",
  secretSecondary: "secret_secondary",
  description: "description",
  customHeaders: "custom_headers",
  metadata: "metadata",
  status: "status",
  disabledAt: "disabled_at",
};

/** The jsonb columns among endpoint fields (need `::jsonb` in pg / stringify in knex). */
export const ENDPOINT_JSON_COLUMNS: readonly string[] = ["metadata", "custom_headers"];

/** True when `column` is one of the endpoint jsonb columns ({@link ENDPOINT_JSON_COLUMNS}). */
export function isEndpointJsonColumn(column: string): boolean {
  return ENDPOINT_JSON_COLUMNS.includes(column);
}

/** Flatten an {@link EndpointPatch} into columns/raw values to SET (undefined keys skipped) — pg. */
export function endpointPatchColumns(patch: EndpointPatch): {
  columns: string[];
  values: unknown[];
} {
  const columns: string[] = [];
  const values: unknown[] = [];
  for (const key of Object.keys(ENDPOINT_PATCH_COLUMN) as (keyof EndpointPatch)[]) {
    if (patch[key] !== undefined) {
      columns.push(ENDPOINT_PATCH_COLUMN[key]);
      values.push(patch[key]);
    }
  }
  return { columns, values };
}

/** Object form of an {@link EndpointPatch} for an UPDATE under `jsonAsText`; jsonb columns stringified. */
export function endpointPatchObject(patch: EndpointPatch): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(ENDPOINT_PATCH_COLUMN) as (keyof EndpointPatch)[]) {
    const value = patch[key];
    if (value === undefined) continue;
    const column = ENDPOINT_PATCH_COLUMN[key];
    out[column] = isEndpointJsonColumn(column) && value != null ? JSON.stringify(value) : value;
  }
  return out;
}

const TRANSITION_COLUMN: Record<keyof Transition, string> = {
  status: "status",
  attempts: "attempts",
  availableAt: "available_at",
  lockedAt: "locked_at",
  lockedBy: "locked_by",
  lastError: "last_error",
  dispatchedAt: "dispatched_at",
};

/** Flatten a {@link Transition} into the columns/values to SET (undefined keys are skipped). */
export function transitionColumns(t: Transition): { columns: string[]; values: unknown[] } {
  const columns: string[] = [];
  const values: unknown[] = [];
  for (const key of Object.keys(TRANSITION_COLUMN) as (keyof Transition)[]) {
    const value = t[key];
    if (value !== undefined) {
      columns.push(TRANSITION_COLUMN[key]);
      values.push(value);
    }
  }
  return { columns, values };
}

/** Ordered attempt values for a knex.raw bind (jsonb column stringified), matching {@link ATTEMPT_COLUMNS}. */
export function attemptValuesStringified(id: string, a: NewDeliveryAttempt): unknown[] {
  const obj = attemptObject(id, a);
  return ATTEMPT_COLUMNS.map((c) => obj[c]);
}

/** Ordered outbox values with the jsonb `payload` stringified, matching {@link OUTBOX_COLUMNS}. */
export function outboxValuesStringified(row: NewOutboxRow): unknown[] {
  const obj = outboxObject(row);
  return OUTBOX_COLUMNS.map((c) => obj[c]);
}

/** Ordered endpoint values with the jsonb columns stringified, matching {@link ENDPOINT_COLUMNS}. */
export function endpointValuesStringified(ep: NewEndpointRow): unknown[] {
  const obj = endpointObject(ep);
  return ENDPOINT_COLUMNS.map((c) => obj[c]);
}

/** Secret-free outbox columns (omits `secret_snapshot`), plus `seq` for the keyset cursor. */
export const OUTBOX_LIST_COLUMNS = [
  "id",
  "event_type",
  "payload",
  "endpoint_id",
  "target_url",
  "status",
  "attempts",
  "available_at",
  "locked_at",
  "locked_by",
  "idempotency_key",
  "last_error",
  "created_at",
  "dispatched_at",
  "seq",
] as const;

/** Secret-free endpoint columns (omits `secret`/`secret_secondary`). */
export const ENDPOINT_LIST_COLUMNS = [
  "id",
  "url",
  "status",
  "description",
  "consecutive_failures",
  "disabled_at",
  "metadata",
  "created_at",
] as const;
